from __future__ import annotations

import random

DECK = [
    ('The Fool','A leap, openness, and the willingness to step into something not fully mapped.','Hesitation, reckless escape, or fear disguised as freedom.'),
    ('The Magician','Power, initiative, and the ability to turn intention into action.','Scattered energy, weak follow-through, or trying to force a result.'),
    ('The High Priestess','Intuition, hidden knowledge, and the need to listen beneath the noise.','Confusion, avoidance of inner truth, or overthinking what you already sense.'),
    ('The Empress','Abundance, attraction, comfort, and a fertile period for growth.','Smothering, stagnation, or comfort becoming complacency.'),
    ('The Emperor','Structure, control, and the need for clear standards or boundaries.','Rigidity, ego, or unstable authority.'),
    ('The Hierophant','Tradition, mentorship, and wisdom within established forms.','Empty rules, stale beliefs, or resisting needed guidance.'),
    ('The Lovers','Union, alignment, attraction, and meaningful choice.','Misalignment, mixed signals, or acting against deeper truth.'),
    ('The Chariot','Momentum, control, and pushing forward with purpose.','Loss of direction, inner conflict, or movement without control.'),
    ('Strength','Quiet power, emotional steadiness, and disciplined softness.','Self-doubt, reactive behavior, or forced confidence.'),
    ('The Hermit','Reflection, solitude, and wisdom gained by stepping back.','Isolation, over-withdrawal, or refusing guidance.'),
    ('Wheel of Fortune','Change, timing, and a larger cycle turning.','Resistance to change or feeling stuck in repetition.'),
    ('Justice','Truth, accountability, and consequences that make sense.','Bias, denial, or avoiding the full picture.'),
    ('The Hanged Man','Pause, surrender, and seeing from a different angle.','Delay without growth or refusing the needed pause.'),
    ('Death','Ending, shedding, and necessary transformation.','Clinging to what is already over.'),
    ('Temperance','Balance, healing, and patient integration.','Extremes, impatience, or inner imbalance.'),
    ('The Devil','Attachment, temptation, and the grip of unhealthy patterns.','Breaking a pattern, or seeing the chain clearly.'),
    ('The Tower','Disruption, truth breaking through, and forced change.','Avoided collapse, delayed truth, or unstable foundations.'),
    ('The Star','Hope, renewal, and trust in what is slowly opening.','Discouragement, disconnection, or dimmed faith.'),
    ('The Moon','Uncertainty, emotion, projection, and unclear terrain.','Things surfacing, illusion thinning, or hidden fear being named.'),
    ('The Sun','Clarity, confidence, visibility, and joyful momentum.','Temporary cloudiness, delayed warmth, or reduced clarity.'),
    ('Judgement','Wake-up call, reckoning, and a chance to respond honestly.','Avoiding the lesson or being too harsh with yourself.'),
    ('The World','Completion, integration, and stepping into a fuller chapter.','Something unfinished or a threshold not fully crossed.'),
    ('Ace of Cups','Fresh feeling, openness of heart, and emotional beginning.','Blocked feeling or emotion held too tightly.'),
    ('Ace of Pentacles','A grounded new start, practical opportunity, or something real taking root.','A missed opening, weak foundation, or hesitation around receiving.'),
    ('Ace of Swords','Truth cutting through, mental clarity, and a decisive insight.','Confusion, distorted thinking, or truth not yet fully faced.'),
    ('Ace of Wands','Spark, desire, initiative, and a live creative charge.','Low energy, hesitation, or inspiration with no channel.'),
    ('Two of Cups','Mutuality, connection, and emotional reciprocity.','Mismatch, imbalance, or one-sided effort.'),
    ('Two of Swords','Stalemate, avoidance, or a choice delayed by overprotection.','Truth creeping in, tension rising, and indecision becoming costly.'),
    ('Two of Wands','Planning, possibility, and standing at the edge of a bigger move.','Playing small, fear of expansion, or waiting too long.'),
    ('Three of Cups','Joy, support, friendship, and emotional uplift through others.','Social messiness, overindulgence, or feeling outside the circle.'),
    ('Three of Pentacles','Collaboration, visible skill, and building something with care.','Misalignment in teamwork or work not meeting the standard.'),
    ('Three of Swords','Heartbreak, disappointment, or painful clarity.','Healing after pain or pain that is still being resisted.'),
    ('Three of Wands','Expansion, anticipation, and the first signs of forward motion.','Frustrated progress or a future vision that lacks execution.'),
    ('Four of Cups','Emotional withdrawal, boredom, or not seeing what is being offered.','Re-engagement, openness, or a new willingness to feel.'),
    ('Four of Pentacles','Holding on, guarding resources, and fear around loss.','Loosening control or instability around what you value.'),
    ('Four of Swords','Rest, recovery, and strategic stillness.','Restlessness, burnout, or refusing the reset you need.'),
    ('Four of Wands','Stability, celebration, and a supportive foundation.','Instability at home or joy that feels delayed.'),
    ('Five of Cups','Grief, fixation on loss, and difficulty seeing what remains.','Turning back toward what is still possible.'),
    ('Five of Pentacles','Lack, exclusion, or fear around support and security.','Recovery, help nearby, or the beginning of relief.'),
    ('Five of Swords','Conflict, ego, and winning at a cost.','Repair, regret, or walking away from petty war.'),
    ('Five of Wands','Friction, competition, and noisy conflicting energies.','Conflict settling or avoiding challenge that would sharpen you.'),
    ('Six of Cups','Memory, sweetness, nostalgia, and the pull of the familiar.','Staying too attached to an older emotional script.'),
    ('Six of Pentacles','Exchange, support, generosity, and balance in giving/receiving.','Strings attached, imbalance, or dependence.'),
    ('Six of Swords','Transition, release, and movement toward calmer water.','Trouble letting go or carrying too much into the next chapter.'),
    ('Six of Wands','Recognition, confidence, and visible success.','Need for validation or success feeling unsteady.'),
    ('Seven of Cups','Options, fantasy, and the temptation of too many possibilities.','Narrowing focus or seeing through illusion.'),
    ('Seven of Pentacles','Patience, evaluation, and asking whether the effort is worth it.','Impatience or draining energy into something with weak return.'),
    ('Seven of Swords','Strategy, concealment, or acting sideways instead of directly.','Truth surfacing, self-deception cracking, or cleaner tactics needed.'),
    ('Seven of Wands','Defensiveness, courage, and holding your ground under pressure.','Exhaustion, collapse of boundaries, or fighting from depletion.'),
    ('Eight of Cups','Leaving behind what no longer feeds the soul.','Avoidance, unfinished departure, or fear of necessary loss.'),
    ('Eight of Pentacles','Practice, skill-building, and focused improvement.','Busy work, weak discipline, or effort without refinement.'),
    ('Eight of Swords','Mental trapping, fear, or a story that shrinks your options.','Release beginning, perspective widening, or fear being named.'),
    ('Eight of Wands','Speed, momentum, and events moving quickly.','Delays, scattered motion, or crossed signals.'),
    ('Nine of Cups','Pleasure, satisfaction, and desire landing well.','Overindulgence, emptiness after getting what you wanted, or shallow fulfillment.'),
    ('Nine of Pentacles','Self-sufficiency, earned ease, and cultivated taste.','Dependence, fragility, or comfort that hides isolation.'),
    ('Nine of Swords','Anxiety, mental spirals, and fear amplified in the dark.','Relief beginning or the fear losing some power.'),
    ('Nine of Wands','Guarded persistence, resilience, and weary boundaries.','Exhaustion, defensiveness, or expecting a hit before it comes.'),
    ('Page of Cups','Curiosity, tenderness, and emotional messages.','Immaturity, mixed signals, or over-romanticizing.'),
    ('Page of Pentacles','A practical beginning, study, and grounded opportunity.','Lack of follow-through or weak commitment to the opportunity.'),
    ('Page of Swords','Alertness, curiosity, and restless mental energy.','Spying, scattered focus, or reactive communication.'),
    ('Page of Wands','Adventure, spark, and a playful invitation to begin.','False start, low confidence, or energy without a plan.'),
    ('Knight of Cups','Romance, invitation, and moving toward what the heart wants.','Idealization, inconsistency, or promise without grounding.'),
    ('Knight of Pentacles','Steadiness, method, and dependable effort.','Stagnation, over-caution, or joyless grinding.'),
    ('Knight of Swords','Fast movement, sharp intent, and direct pursuit.','Impulsiveness, aggression, or rushing without wisdom.'),
    ('Knight of Wands','Bold pursuit, heat, and dramatic forward energy.','Chaos, inconsistency, or energy that burns too hot.'),
    ('Queen of Cups','Emotional depth, compassion, and intuitive receptivity.','Blurred boundaries, moodiness, or taking in too much.'),
    ('Queen of Pentacles','Grounded care, resourcefulness, and practical warmth.','Overextension or care that neglects the self.'),
    ('Queen of Swords','Discernment, honesty, and clear-eyed independence.','Bitterness, coldness, or cutting too quickly.'),
    ('Queen of Wands','Magnetism, confidence, and self-possessed creative fire.','Insecurity covered by performance or envy in the room.'),
    ('King of Cups','Emotional mastery, calm authority, and measured feeling.','Suppression, moodiness, or emotional control issues.'),
    ('King of Pentacles','Stable success, stewardship, and mature material judgment.','Control, greed, or values flattening into pure security.'),
    ('King of Swords','Clarity, strategy, and authoritative reasoning.','Harsh judgment, detachment, or cleverness without heart.'),
    ('King of Wands','Vision, leadership, and bold but directed fire.','Domineering force, ego, or inspiration with weak discipline.'),
    ('Ten of Cups','Emotional fulfillment, belonging, and heart-level harmony.','Disconnection, idealized family story, or happiness that needs repair.'),
    ('Ten of Pentacles','Long-term stability, legacy, and secure structure.','Instability in the long game or values out of alignment.'),
    ('Ten of Swords','Painful ending, finality, and no more pretending.','Recovery, surviving the worst, and refusing a dead story.'),
    ('Ten of Wands','Burden, overcommitment, and carrying too much alone.','Release, delegation, or refusing unnecessary weight.'),
]

SPREADS = {
    'single': {'name': 'Single card', 'positions': ['Message']},
    'three': {'name': 'Past · Present · Advice', 'positions': ['Past', 'Present', 'Advice']},
    'crossroads': {'name': 'Situation · Obstacle · Advice · Direction', 'positions': ['Situation', 'Obstacle', 'Advice', 'Direction']},
    'relationship': {'name': 'How they feel · What is hidden · What to do', 'positions': ['How they feel', 'What is hidden', 'What to do']},
}


def draw_cards(spread_key: str) -> list[dict]:
    spread = SPREADS[spread_key]
    pool = list(DECK)
    picked = []
    for pos in spread['positions']:
        name, upright, reversed_meaning = pool.pop(random.randrange(len(pool)))
        picked.append({
            'name': name,
            'position': pos,
            'orientation': 'upright' if random.random() < 0.74 else 'reversed',
            'meanings': {'upright': upright, 'reversed': reversed_meaning},
        })
    return picked
